### ISSUE TITLE
Remove API key for security purposes

### ISSUE THREAD

**Issue by cjappl** [MidpriceDog/the-odds-api-client#6]
Hi!

I wanted to leave a friendly suggestion that you should consider removing the API key from this github. It would be easy for some nefarious actor to use it and have you run out of requests.

You could consider removing it, then adding that file name to your .gitignore then killing the old key in your account so it was no longer hooked up to anything.

Cheers

**Comment by MidpriceDog** [comment]
Hello!

Thanks for raising this issue. That key has long since been reset so it poses no security issues as it is not active / valid. Definitely should not have been committed in the first place though!

**Comment by cjappl** [comment]
Perfect!

Thanks for the nice repo.
